### ISSUE TITLE
Organism with arguments in initialize

### ISSUE THREAD

**Issue by dukedave** [dorkrawk/darwinning#17]
Is there any way to specify arguments to be passed in to the organism's `initialize`?

E.g: Consider [the example in the README](https://github.com/dorkrawk/darwinning/tree/b6795c92698a5c15acb8fc7b6ccc6be3af06c836#include-style), how could I modify this so I can pass in the target number, instead of having it hard coded to `100`?

**Comment by dorkrawk** [comment]
Sure, you can define your `fitness` method any way you want. For example you could write something like this:

```ruby
require 'darwinning'

class Triple
  include Darwinning

  ...

  def initialize(target_sum)
    @target_sum = target_sum
  end

  def fitness
    # Try to get the sum of the 3 digits to add up to 100
    (first_number + second_number + third_number - @target_sum).abs
  end
end
```

**Comment by dukedave** [comment]
Sorry, I should have been more clear.

So I had something similar to that, but when I used the snippet showing how to call `evolve!`, I get the following error:

```
est.rb:14:in `initialize': wrong number of arguments (given 0, expected 1) (ArgumentError)
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:101:in `new'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:101:in `build_member'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:31:in `block in build_population'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:30:in `times'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:30:in `build_population'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning/population.rb:25:in `initialize'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning.rb:18:in `new'
        from /usr/local/bundle/gems/darwinning-0.1.1/lib/darwinning.rb:18:in `build_population'
        from test.rb:25:in `<main>'
```

:arrow_up: that is from [this](https://gist.github.com/dukedave/a01c13fc1e64cde00da893c435f2b649).
